# Generated by Django 5.0.6 on 2024-08-01 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0002_rename_title_test_name_remove_test_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="group",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="testapp.group",
            ),
            preserve_default=False,
        ),
    ]
