# Generated by Django 5.0.6 on 2024-08-01 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0003_test_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="testapp.group",
            ),
        ),
    ]
