# Generated by Django 5.0.6 on 2024-07-31 04:00

from django.db import migrations


def set_default_test(apps, schema_editor):
    Test = apps.get_model('testapp', 'Test')
    Word = apps.get_model('testapp', 'Word')
    Group = apps.get_model('testapp', 'Group')

    # デフォルトのグループとテストを作成
    default_group, created = Group.objects.get_or_create(name='Default Group')
    default_test, created = Test.objects.get_or_create(title='Default Test', description='Default Description', group=default_group)

    # デフォルトのテストを設定
    Word.objects.filter(test__isnull=True).update(test=default_test)

class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0015_remove_test_words_word_test_alter_test_group'),  # 既存の最新のマイグレーションに合わせて調整
    ]

    operations = [
        migrations.RunPython(set_default_test),
    ]
