# Generated by Django 5.0.6 on 2024-07-31 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0016_alter_test_group"),
    ]

    operations = []
